name: thinkcraft_flutter
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.2
  go_router: ^14.6.2
  logger: ^2.5.0
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  speech_to_text: ^7.3.0
  flutter_sound: ^9.4.12
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.13.0
  flutter_keyboard_visibility: ^5.4.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  path_provider: ^2.1.2
  sentry_flutter: ^7.15.0
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
