name: thinkcraft_flutter
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.2
  go_router: ^14.6.2
  logger: ^2.5.0
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
